- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: from play level
  vars_files:
  - course.yml
  vars_prompt:
  - name: NAME 
    prompt: What is your NAME?
    private: false
  - name: print course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duratioin: {{ DURATION }}, Trainer: {{ Trainer }}"