- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id roboshop
    ignore_error: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"